apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-secret-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  namespace: basegun-preprod
  name: token-github
  annotations:
    kubernetes.io/service-account.name: github
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: github-secret-rolebinding
subjects:
- kind: ServiceAccount
  name: github
  apiGroup: ""
roleRef:
  kind: Role
  name: create-secret-role
  apiGroup: ""
  