categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🔥 Enhancements'
    labels:
      - 'enhancement'
autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+'
      - '/hotfix\/.+'
      - '/bug\/.+'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
  - label: 'enhancement'
    branch:
      - '/enhancement\/.+/'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Changes

  $CHANGES
