include:
  - project: $CATALOG_PATH
    file: vault-ci.yml
    ref: main
  - project: $CATALOG_PATH
    file: kaniko-ci.yml
    ref: main

default:
  image: python:3.9-slim-buster


variables:
  http_proxy: $http_proxy
  https_proxy: $http_proxy
  no_proxy: $no_proxy
  HTTP_PROXY: $http_proxy
  HTTPS_PROXY: $http_proxy
  NO_PROXY: $no_proxy
  TAG: "${CI_COMMIT_REF_SLUG}"
  REGISTRY_URL: "${REGISTRY_HOST}/${PROJECT_PATH}"

stages:
  - read-secret
  # - test-app
  - build-docker

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

# test:
#   image: python:3.9-slim-buster
#   stage: test-app
#   variables:
#     OS_USERNAME: data
#     OS_PASSWORD: data
#     OS_PROJECT_NAME: data
#   script:
#     - pip install --upgrade pip && pip install --no-cache-dir -f https://download.pytorch.org/whl/cpu/torch_stable.html -r backend/requirements/common.txt -r backend/requirements/dev.txt
#     - python -m unittest discover -v -s ./backend
#   allow_failure: true

build_docker_front:
  variables:
    WORKING_DIR: 'frontend'
    IMAGE_NAMES: 'frontend'
    DOCKERFILE: 'frontend/Dockerfile'
  stage: build-docker
  extends:
    - .kaniko:build-push

build_docker_back:
  variables:
    WORKING_DIR: 'backend'
    IMAGE_NAMES: 'backend'
    DOCKERFILE: 'backend/Dockerfile'
  stage: build-docker
  extends:
    - .kaniko:build-push

# build_docker_logs:
#   variables:
#     WORKING_DIR: 'logs'
#     IMAGE_NAME: 'logs'
#     DOCKERFILE: 'Dockerfile-dso'
#     NO_PROXY: "*,gitlab-op.apps.ocp4-8.infocepo.com,dindservice,quay.apps.ocp4-8.infocepo.com"
#     no_proxy: "*,gitlab-op.apps.ocp4-8.infocepo.com,dindservice,quay.apps.ocp4-8.infocepo.com"
#   stage: build-docker
#   extends:
#     - .docker:build
#   tags:
#     - docker
#     - vms
