version: '3.8'

services:

  backend:
    profiles:
        - all
        - backend-only
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - VERSION=${TAG}
        - CACERT_LOCATION
      context: ./backend
      target: ${BUILD_TARGET:-dev}
    container_name: basegun-backend
    environment:
      - PATH_LOGS=/app/logs
      - OS_USERNAME
      - OS_PASSWORD
      - OS_PROJECT_NAME
      - http_proxy
      - https_proxy
      - no_proxy
      - WORKSPACE=dev
      - REQUESTS_CA_BUNDLE=$CACERT_LOCATION
    image: basegun-backend:${TAG}-dev
    ports:
      - 5000:5000
    volumes:
      - $PWD/backend/src:/app/src
      - $PWD/backend/tests:/app/tests
      - $PWD/backend/logs:/app/logs
      - /app/src/weights

  frontend:
    profiles:
        - all
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - NODE_EXTRA_CA_CERTS=$CACERT_LOCATION
      context: ./frontend
      target: dev
    image: basegun-frontend:${TAG}-dev
    container_name: basegun-frontend
    ports:
      - 3000:5173
      - 4173:4173
    volumes:
      - $PWD/frontend/src:/app/src
      - /app/node_modules
