version: '3.8'

services:

  backend:
    build:
      args:
        - VERSION=${TAG}
      context: ./backend
      target: prod
    container_name: basegun-backend
    environment:
      - PATH_LOGS=/app/logs
      - OS_USERNAME
      - OS_PASSWORD
      - OS_PROJECT_NAME
      - WORKSPACE=${WORKSPACE:-prod}
    image: basegun-backend:${TAG}-prod
    ports:
      - 5000:5000
    volumes:
      - /var/log/basegun:/app/logs

  frontend:
    build:
      args: 
        - VITE_WORKSPACE=$WORKSPACE
      context: ./frontend
      target: prod
    container_name: basegun-frontend
    # environment:
    #   - VITE_WORKSPACE=${WORKSPACE:-prod}
    image: basegun-frontend:${TAG}-prod
    ports:
      - ${PORT_PROD:-80}:80

  filebeat:
    image: elastic/filebeat:6.5.4
    user: root
    container_name: filebeat
    environment:
      - X_OVH_TOKEN
      - API_OVH_TOKEN
    volumes:
      - $PWD/infra/filebeat.elastic.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log/basegun:/var/log/basegun
    command: bash -c "sleep 30 && filebeat -e --strict.perms=false"