version: '3.8'

services:

  backend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      context: ./backend
      target: dev
    container_name: basegun-backend
    environment:
      - PATH_IMGS=/app/images
      - PATH_LOGS=/app/logs
      - VERSION=${TAG}
    image: basegun-backend:${TAG}-dev
    ports:
      - 5000:5000
    volumes:
      - /tmp/basegun:/app/images
      - $PWD/backend/src:/app/src
      # - $PWD/backend/tests:/app/tests
      - $PWD/backend/logs:/app/logs
      - /app/src/weights

  frontend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      context: ./frontend
      target: dev
    image: basegun-frontend:${TAG}-dev
    container_name: basegun-frontend
    ports:
      - 3000:3000
    volumes:
      - /tmp/basegun:/app/public/temp
      - $PWD/frontend/src:/app/src
      - /app/node_modules

  filebeat:
    image: elastic/filebeat:8.1.2
    user: root
    environment:
      - OVH_TOKEN=$OVH_TOKEN
    volumes:
      - $PWD/infra/filebeat.logstash.yml:/usr/share/filebeat/filebeat.yml:ro
      - $PWD/backend/logs:/var/log/basegun
    command: ["filebeat", "-e", "--strict.perms=false"]