version: '3.8'

services:

  backend:
    build:
      args:
        - VERSION=${TAG}
      context: ./backend
      target: ${BUILD_TARGET:-prod}
    container_name: basegun-backend
    environment:
      - PATH_LOGS=/tmp/logs
      - OS_USERNAME
      - OS_PASSWORD
      - OS_PROJECT_NAME
      - WORKSPACE=${WORKSPACE:-prod}
    image: basegun-backend:${TAG}-prod
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
      target: prod
    container_name: basegun-frontend
    image: basegun-frontend:${TAG}-prod
    ports:
      - ${PORT_PROD:-80}:8080