version: '3.8'

services:

  backend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      context: ./backend
      target: prod
    container_name: basegun-backend
    environment:
      - PATH_IMGS=/app/images
      - PATH_LOGS=/app/logs
      - VERSION=${TAG}
      - OS_USERNAME
      - OS_PASSWORD
      - OS_PROJECT_NAME
      - OS_REGION_NAME
    image: basegun-backend:${TAG}-prod
    ports:
      - 5000:5000

  frontend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      context: ./frontend
      target: prod
    container_name: basegun-frontend
    image: basegun-frontend:${TAG}-prod
    ports:
      - ${PORT_PROD:-80}:80

  filebeat:
    image: elastic/filebeat:6.5.4
    user: root
    environment:
      - http_proxy
      - https_proxy
      - X_OVH_TOKEN
      - API_OVH_TOKEN
    volumes:
      - $PWD/infra/filebeat.elastic.yml:/usr/share/filebeat/filebeat.yml:ro
      - $PWD/backend/logs:/var/log/basegun
    command: bash -c "sleep 30 && filebeat -e --strict.perms=false"