version: '3.8'

services:

  backend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - VERSION=${TAG}
      context: ./backend
      target: ${BUILD_TARGET:-dev}
    container_name: basegun-backend
    environment:
      - PATH_IMGS=/app/images
      - PATH_LOGS=/app/logs
      - OS_USERNAME
      - OS_PASSWORD
      - OS_PROJECT_NAME
      - http_proxy
      - https_proxy
      - WORKSPACE=dev
    image: basegun-backend:${TAG}-dev
    ports:
      - 5000:5000
    volumes:
      - /tmp/basegun:/app/images
      - $PWD/backend/src:/app/src
      - $PWD/backend/tests:/app/tests
      - $PWD/backend/logs:/app/logs
      - /app/src/weights

  frontend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      context: ./frontend
      target: dev
    image: basegun-frontend:${TAG}-dev
    container_name: basegun-frontend
    ports:
      - 3000:3000
    volumes:
      - /tmp/basegun:/app/public/temp
      - $PWD/frontend/src:/app/src
      - /app/node_modules
