version: '3.8'

services:

  backend:
    image: basegun-back:${TAG}-prod
    build:
      context: ./backend
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - PATH_IMGS=/app/images
    ports:
      - 5000:5000
    volumes:
      - /tmp/basegun:/app/images

  frontend:
    image: basegun-front:${TAG}-prod
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      context: ./frontend
      target: prod
    ports:
      - 80:80
    volumes:
      - /tmp/basegun:/usr/share/nginx/html/temp
