version: '3.8'

services:

  backend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      context: ./backend
      target: prod
    container_name: basegun-backend
    environment:
      - PATH_IMGS=/app/images
    image: basegun-backend:${TAG}-prod
    ports:
      - 5000:5000
    volumes:
      - /tmp/basegun:/app/images

  frontend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      context: ./frontend
      target: prod
    container_name: basegun-frontend
    image: basegun-frontend:${TAG}-prod
    ports:
      - ${PORT_PROD:-80}:80
    volumes:
      - /tmp/basegun:/usr/share/nginx/html/temp
