version: '3.8'

services:

  backend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - VERSION=${TAG}
      context: ./backend
      target: prod
    container_name: basegun-backend
    environment:
      - PATH_IMGS=/app/images
      - PATH_LOGS=/app/logs
      - WORKSPACE
    image: basegun-backend:${TAG}-prod
    ports:
      - 5000:5000
    volumes:
      - /tmp/basegun:/app/images
      - /var/log/basegun:/app/logs

  frontend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
      context: ./frontend
      target: prod
    container_name: basegun-frontend
    image: basegun-frontend:${TAG}-prod
    ports:
      - ${PORT_PROD:-80}:80
    volumes:
      - /tmp/basegun:/usr/share/nginx/html/temp

  filebeat:
    image: elastic/filebeat:6.5.4
    user: root
    container_name: filebeat
    environment:
      - X_OVH_TOKEN
      - API_OVH_TOKEN
    volumes:
      - $PWD/infra/filebeat.elastic.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log/basegun:/var/log/basegun
    command: bash -c "sleep 30 && filebeat -e --strict.perms=false"