version: '3.8'
services:
  backend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - VERSION=${TAG:-2.0}
        - CACERT_LOCATION
      context: ./backend
      target: ${BUILD_TARGET:-dev}
    container_name: basegun-backend
    environment:
      - S3_URL_ENDPOINT=${S3_URL_ENDPOINT:-http://minio:9000}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-minioadmin}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-minioadmin}
      - http_proxy
      - https_proxy
      - UVICORN_LOG_LEVEL=${UVICORN_LOG_LEVEL}
      - LOG_LEVEL=${UVICORN_LOG_LEVEL}
      - no_proxy
      - WORKSPACE=dev
      - REQUESTS_CA_BUNDLE=$CACERT_LOCATION
    image: basegun-backend:${TAG:-2.0}-dev
    ports:
      - 5000:5000
    volumes:
      - $PWD/backend/src:/app/src
      - $PWD/backend/tests:/app/tests
      - $PWD/backend/logs:/tmp/logs
      - /app/src/weights

  frontend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - NODE_EXTRA_CA_CERTS=$CACERT_LOCATION
      context: ./frontend
      target: ${BUILD_TARGET:-dev}
    image: basegun-frontend:${TAG:-2.0}-dev
    container_name: basegun-frontend
    ports:
      - 8080:80 # if BUILD_TARGET = prod
      - 3000:5173
      # - 4173:4173 
    volumes:
      - $PWD/frontend/src:/app/src
      - /app/node_modules

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
