ingress.hosts[0].host: basegun.interieur.gouv.fr
backend.image.repository: registry.dso.interieur.rie.gouv.fr/mi-basegun/basegun-backend
frontend.image.repository: registry.dso.interieur.rie.gouv.fr/mi-basegun/basegun-frontend