nameOverride: ""
fullnameOverride: ""
ingress:
  enabled: true
  className: ""
  hosts:
    - host: basegun.dev.numerique-interieur.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
serviceAccount:
  create: true
  annotations: {}
  name: ""
imagePullSecrets:
  - name: registry-pull-secret
backend:
  replicaCount: 1
  image:
    repository: harbor.apps.c6.numerique-interieur.com/mi-basegun-test/basegun-backend
    tag: develop
  logs:
    repository: ghcr.io/datalab-mi/basegun/filebeat-rootless
    tag: 6.5.4
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5000
    containerPort: 5000
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  config:
    workspace: preprod
  secret:
    create: false
    sops: true
    secretName: basegun-preprod-secret
  resources:
    limits:
      cpu: 2500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
frontend:
  replicaCount: 1
  image:
    repository: harbor.apps.c6.numerique-interieur.com/mi-basegun-test/basegun-frontend
    pullPolicy: Always
    tag: develop
  service:
    type: ClusterIP
    port: 8080
    containerPort: 8080
  resources: {}