nameOverride: ""
fullnameOverride: ""
env: dev
ingress:
  enabled: true
  className: ""
  hosts:
    - host: basegun.fr
      paths:
        - path: /
          pathType: Prefix
  tls: []
serviceAccount:
  create: true
  annotations: {}
  name: ""
backend:
  replicaCount: 1
  image:
    repository: ghcr.io/datalab-mi/basegun/basegun-backend
    pullPolicy: IfNotPresent
    tag: "3.2"
    imagePullSecrets: []
  logs:
    repository: elastic/filebeat
    tag: 6.5.4
    pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  service:
    type: ClusterIP
    port: 80
    containerPort: 5000
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  config:
    workspace: preprod
  secret:
    create: false
    sops: false
    secretName: basegun-secret
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/datalab-mi/basegun/basegun-frontend
    pullPolicy: IfNotPresent
    tag: "3.2"
    imagePullSecrets: []
  service:
    type: ClusterIP
    port: 80
    containerPort: 8080
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
