#cloud-config

package_update: true
packages:
 - curl
 - make

write_files:
  - path: /etc/ssh/sshd_config
    content: |
         Port 4444
         PermitRootLogin no
         PasswordAuthentication no
    append: true

bootcmd:
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
  - chmod +x /usr/bin/docker-compose

final_message: "The system is finally up, after $UPTIME seconds"

