---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basegun-backend
  namespace: basegun
spec:
  selector:
    matchLabels:
      app: basegun-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: basegun-backend
    spec:
      containers:
        - name: basegun-backend
          imagePullPolicy: Always
          image: "ghcr.io/datalab-mi/basegun/basegun-backend:1.2"
          ports:
            - containerPort: 5000
          resources: {}
          env:
            - name: OS_USERNAME
              value: ""
            - name: OS_PROJECT_NAME
              value: ""
            - name: OS_PASSWORD
              value: ""
            - name: WORKSPACE
              value: "dev"
            - name: PATH_IMGS
              value: /app/images
            - name: PATH_LOGS
              value: /app/logs
---
apiVersion: v1
kind: Service
metadata:
  name: basegun-backend
  namespace: basegun
spec:
  selector:
    app: basegun-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000