---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basegun-backend
  namespace: basegun
spec:
  selector:
    matchLabels:
      app: basegun-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: basegun-backend
    spec:
      containers:
        # basegun container
        - name: basegun-backend
          #imagePullPolicy: Always
          image: ghcr.io/datalab-mi/basegun/basegun-backend:1.5
          ports:
            - containerPort: 5000
          env:
            - name: OS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: basegun-secret
                  key: OS_USERNAME
            - name: OS_PROJECT_NAME
              valueFrom:
                secretKeyRef:
                  name: basegun-secret
                  key: OS_PROJECT_NAME
            - name: OS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: basegun-secret
                  key: OS_PASSWORD
            - name: WORKSPACE
              valueFrom:
                configMapKeyRef:
                  name: basegun-config
                  key: WORKSPACE
            - name: PATH_IMGS
              valueFrom:
                configMapKeyRef:
                  name: basegun-config
                  key: PATH_IMGS
            - name: PATH_LOGS
              value: /app/logs
          # Check if app is alive
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            # wait 10s for the first probe
            initialDelaySeconds: 10
            # each 60s verify if app is ready
            periodSeconds: 60
          resources: {}  # TODO: choose limits
          volumeMounts:
            - name: logs
              mountPath: /app/logs
        # filebeat container
        - name: filebeat
          image: elastic/filebeat:6.5.4
          command: ["/bin/bash"]
          args: ["-c", "filebeat -e --path.config /tmp/filebeat/ --strict.perms=false"]
          env:
            - name: X_OVH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: basegun-secret
                  key: X_OVH_TOKEN
            - name: API_OVH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: basegun-secret
                  key: API_OVH_TOKEN
          resources: {} # TODO: choose limits
          volumeMounts:
            - name: filebeat-conf
              mountPath: /tmp/filebeat/
            - name: logs
              mountPath: /var/log/basegun
      volumes:
        - name: filebeat-conf
          configMap:
            name: filebeat-config
            items:
              - key: filebeat.elastic.yml
                path: filebeat.yml
        - name: basegun-secret
          secret:
            secretName: basegun-secret
        - name: logs
          emptyDir: {}


---
apiVersion: v1
kind: Service
metadata:
  name: basegun-backend
  namespace: basegun
spec:
  selector:
    app: basegun-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000