version: '3'

services:
  reverse-proxy:
    image: traefik:v2.6
    container_name: traefik
    restart: unless-stopped
    volumes:
      - $PWD/infra/traefik/conf/:/etc/traefik/conf/
      - /var/log/traefik:/logs
      - $PWD/infra/traefik/acme.json:/acme.json
    # ports:
    #   - 80:80
    #   - 443:443
    network_mode: host
    environment:
      # entrypoint web, websecure metrics and dashboard
      TRAEFIK_ENTRYPOINTS_web_ADDRESS: :80
      TRAEFIK_ENTRYPOINTS_websecure_ADDRESS: :443
      #TRAEFIK_ENTRYPOINTS_metrics_ADDRESS: :8082
      # use file provider
      TRAEFIK_PROVIDERS_FILE_DIRECTORY: ${TRAEFIK_PROVIDERS_FILE_DIRECTORY:-/etc/traefik/conf/}
      TRAEFIK_PROVIDERS_FILE_WATCH: "true"
      # redirection web to websecure globaly (not work with http challenge)
      #TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_PERMANENT: "true"
      #TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_TO: websecure
      #TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: https
      # http challenge lets encrypt
      TRAEFIK_CERTIFICATESRESOLVERS_resolver: "true"
      TRAEFIK_CERTIFICATESRESOLVERS_resolver_ACME_EMAIL: basegun@interieur.gouv.fr
      TRAEFIK_CERTIFICATESRESOLVERS_resolver_ACME_HTTPCHALLENGE: "true"
      TRAEFIK_CERTIFICATESRESOLVERS_resolver_ACME_HTTPCHALLENGE_ENTRYPOINT: web
      TRAEFIK_CERTIFICATESRESOLVERS_resolver_ACME_STORAGE: acme.json
      # dashboard
      TRAEFIK_API: "false"
      TRAEFIK_API_DASHBOARD: "false"
      # logs
      TRAEFIK_LOG_LEVEL: ${TRAEFIK_LOG_LEVEL:-INFO}
      TRAEFIK_ACCESSLOG: ${TRAEFIK_ACCESSLOG:-true}
      TRAEFIK_ACCESSLOG_FORMAT: ${TRAEFIK_ACCESSLOG:-common}
      TRAEFIK_ACCESSLOG_FILEPATH: ${TRAEFIK_ACCESSLOG_FILEPATH:-/logs/traefik.log}
      TRAEFIK_LOG_FILEPATH: ${TRAEFIK_LOG_FILEPATH:-/logs/access.log}
      TZ: ${TZ:-Europe/Paris}
      # metrics with prometheus
      TRAEFIK_METRICS_PROMETHEUS: "false"
      TRAEFIK_METRICS_PROMETHEUS_ADDENTRYPOINTSLABELS: "false"
      TRAEFIK_METRICS_PROMETHEUS_ADDROUTERSLABELS: "false"
      TRAEFIK_METRICS_PROMETHEUS_ADDSERVICESLABELS: "false"
      #TRAEFIK_METRICS_PROMETHEUS_ENTRYPOINT: metrics
      # ping
      TRAEFIK_PING: "false"
      HOST: preprod.basegun.fr
