{{- if .Values.backend.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secret.secretName }}
{{- with .Values.backend.secret.values }}
data:
  {{- toYaml . | nindent 2 }}
{{- end -}}
{{ else }}
{{- if not (lookup "v1" "Secret" .Release.Namespace .Values.backend.secret.secretName ) -}}
{{- fail (printf "Secret %s must be created before" .Values.backend.secret.secretName) -}}
{{- end -}}
{{- end -}}
