{{- if .Values.backend.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secret.secretName }}
{{- with .Values.backend.secret.values }}
stringData:
  {{- toYaml . | nindent 2 | quote }}
{{- end -}}
{{- end -}}


