apiVersion: v1
kind: Service
metadata:
  name: {{ include "basegun.FrontFullname" . }}
  labels:
    {{- include "basegun.FrontLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "basegun.FrontSelectorLabels" . | nindent 4 }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "basegun.BackFullname" . }}
  labels:
    {{- include "basegun.BackLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "basegun.BackSelectorLabels" . | nindent 4 }}