# http routing section
http:
  routers:
    http-web:
      middlewares:
        - http-redirectscheme
      rule: Host(`{{ env "HOST" }}`)
      service: web
    https-web:
      rule: Host(`{{ env "HOST" }}`)
      service: web
      tls:
        certResolver: resolver

  middlewares:
    auth-user:
      basicAuth:
        usersFile: "/etc/traefik/users.conf"
    http-redirectscheme:
      redirectScheme:
        scheme: "https"
        permanent: true
  services:
    # Define how to reach an existing service on our infrastructure
    web:
      loadBalancer:
        servers:
        - url: https://basegun-prod.c5.numerique-interieur.com
