on:
  push:
    branches:
      - "develop"
name: Preprod deployment
jobs:
  build-push-deploy-preprod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: TAG=action docker-compose -f docker-compose-prod.yml build
    - name: Login to GHCR
      if: success()
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Delete previous develop image
      uses: bots-house/ghcr-delete-image-action@v1.0.0
      with:
        owner: datalab-mi/basegun
        name: basegun-frontend
        token: ${{ secrets.PERSO_ACCESS_TOKEN }}
        tag: develop
    - name: Delete previous develop image
      uses: bots-house/ghcr-delete-image-action@v1.0.0
      with:
        owner: datalab-mi/basegun
        name: basegun-backend
        token: ${{ secrets.PERSO_ACCESS_TOKEN }}
        tag: develop
    - name: Push on GHCR
      run: |
        ./cd/scripts/docker-push.sh develop
    - name: Deploy to preprod
      if: success()
      uses: ./.github/workflows/deploy.yml
      with:
        image_version: latest
        branch: "feature/cd"
        volume_size: 10
        flavor: "s1-2"
        workspace: "preprod"
      secrets:
        SERVER_IP: ${{ secrets.PREPROD_SERVER_IP }}
        OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
        OS_PROJECT_ID: ${{ secrets.OS_PROJECT_ID }}
        OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
        OS_USERNAME: ${{ secrets.OS_USERNAME }}

