name: Docker workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
    - name: Test the built containers
      run: |
        docker-compose up -d
        bash tests/test-container.sh
    - name: Login to GHCR
        if: ( success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' ) )
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push on GHCR
      if: ( success() && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' ) )
      run: |
        docker tag basegun_frontend ghcr.io/datalab-mi/basegun/basegun-frontend:latest
        docker tag basegun_backend ghcr.io/datalab-mi/basegun/basegun-backend:latest
        docker push ghcr.io/datalab-mi/basegun/basegun-frontend:latest
        docker push ghcr.io/datalab-mi/basegun/basegun-backend:latest
