name: Sync DSO gitlab repository

on: 
  workflow_dispatch:
  push:
    branches:
      - feature/adapt-infra-for-dso-env

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl "https://gitlab.apps.c6.numerique-interieur.com/api/v4/projects/62/trigger/pipeline" \
            -X POST \
            --fail \
            -F token=${{ secrets.DSO_TOKEN }} \
            -F ref=main \
            -F variables[GIT_BRANCH_DEPLOY]=${{ github.GITHUB_REF_NAME }} \
            -F variables[PROJECT_NAME]=basegun-test/infra
          
