name: Repo sync with Cloud Pi Native

on:
  push:
    branches:
      - "develop"
      - "main"
      - "enh/kube"
  workflow_dispatch:

jobs:
  mirror:
    name: Sync repo with Cloud Pi Native
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3
      - name: Send a sync request to DSO api
        env:
          CI_COMMIT_REF: enh/kube
        run: |
          sh ./infra/scripts/mirror.sh \
            -a ${{ secrets.API_DOMAIN }} \
            -g ${{ secrets.GITLAB_TRIGGER_TOKEN }} \
            -k ${{ secrets.CONSUMER_KEY }} \
            -s ${{ secrets.CONSUMER_SECRET }} \
            -i ${{ secrets.GITLAB_PROJECT_ID }}
