name: CI for pr
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  tag-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag PR
        uses: release-drafter/release-drafter@v5
        with:
          name: PR ${{ github.ref }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-test:
    uses: ./.github/workflows/test-on-kube.yml
    needs: tag-pr
    secrets:
      API_OVH_TOKEN: ${{ secrets.API_OVH_TOKEN }}
      OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
      OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
      OS_USERNAME: ${{ secrets.OS_USERNAME }}
      X_OVH_TOKEN: ${{ secrets.PREPROD_OVH_TOKEN }}
