name: CI for pr
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tag-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Tag PR
      uses: release-drafter/release-drafter@v5
      with:
        name: PR ${{ github.ref }}
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-files-modified:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_modified_files }}
    steps:
    - uses: actions/checkout@v2
    - name: Verify Changed files
      uses: tj-actions/changed-files@v18.4
      id: changed-files
      with:
        base_sha: ${{ github.event.pull_request.base.sha }}

  build-backend-and-test:
    runs-on: ubuntu-latest
    needs: check-files-modified
    if: ( contains(needs.check-files-modified.outputs.changed_files, 'backend/') )
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image for tests
      run: docker build --target test -t basegun-back:tests backend/
    - name: Start container
      run: |
        docker run --rm -e WORKSPACE=preprod --name basegun_back_test -d basegun-back:tests
    - name: Run tests
      run: docker exec basegun_back_test python -m unittest discover -v
