name: Push Docker image to GitHub container
on:
  push:
    tags:
      - 'v*'
jobs:
  release_github:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Publish release
      uses: release-drafter/release-drafter@v5
      with:
        name: ${{ github.ref#refs/tags/ }}
        tag: ${{ github.ref#refs/tags/ }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: TAG=action docker-compose -f docker-compose-prod.yml build
    - name: Login to GHCR
      if: success()
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push on GHCR
      run: |
        docker tag basegun-front:action-prod ghcr.io/datalab-mi/basegun/basegun-frontend:${{ github.ref#refs/tags/ }}
        docker tag basegun-back:action-prod ghcr.io/datalab-mi/basegun/basegun-backend:${{ github.ref#refs/tags/ }}
        docker push ghcr.io/datalab-mi/basegun/basegun-frontend:${{ github.ref#refs/tags/ }}
        docker push ghcr.io/datalab-mi/basegun/basegun-backend:${{ github.ref#refs/tags/ }}
        docker tag ghcr.io/datalab-mi/basegun/basegun-frontend:${{ github.ref#refs/tags/ }} ghcr.io/datalab-mi/basegun/basegun-frontend:latest
        docker tag ghcr.io/datalab-mi/basegun/basegun-backend:${{ github.ref#refs/tags/ }} ghcr.io/datalab-mi/basegun/basegun-backend:latest
        docker push ghcr.io/datalab-mi/basegun/basegun-frontend:latest
        docker push ghcr.io/datalab-mi/basegun/basegun-backend:latest