name: Push Docker image to GitHub container
on:
  push:
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  release_github:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Publish release
      uses: release-drafter/release-drafter@v5
      with:
        name: ${{ steps.get_version.outputs.VERSION }}
        tag: ${{ steps.get_version.outputs.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_push:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: TAG=action docker-compose -f docker-compose-prod.yml build
    - name: Login to GHCR
      if: success()
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Push on GHCR
      run: |
        docker tag basegun-front:action-prod ghcr.io/datalab-mi/basegun/basegun-frontend:${{ steps.get_version.outputs.VERSION }}
        docker tag basegun-back:action-prod ghcr.io/datalab-mi/basegun/basegun-backend:${{ steps.get_version.outputs.VERSION }}
        docker push ghcr.io/datalab-mi/basegun/basegun-frontend:${{ steps.get_version.outputs.VERSION }}
        docker push ghcr.io/datalab-mi/basegun/basegun-backend:${{ steps.get_version.outputs.VERSION }}
        docker tag ghcr.io/datalab-mi/basegun/basegun-frontend:${{ steps.get_version.outputs.VERSION }} ghcr.io/datalab-mi/basegun/basegun-frontend:latest
        docker tag ghcr.io/datalab-mi/basegun/basegun-backend:${{ steps.get_version.outputs.VERSION }} ghcr.io/datalab-mi/basegun/basegun-backend:latest
        docker push ghcr.io/datalab-mi/basegun/basegun-frontend:latest
        docker push ghcr.io/datalab-mi/basegun/basegun-backend:latest