name: Test on kubernetes

on:
  # only work when code is on main branch
  workflow_dispatch:
  push:
    branches:
      - 'enh/kube'


jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: basegun-testing
          wait: 60s
          verbosity: 2

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Set up ingress controller 
        run: |
         cat << EOF > values.yml
         deployment:
           kind: DaemonSet
         ingressClass:
           enabled: true
           isDefaultClass: true
         ports:
           web:
             hostPort: 80
           websecure:
             hostPort: 443
         service:
           type: ClusterIP
         EOF
         helm repo add traefik https://traefik.github.io/charts && helm repo update
         helm install --namespace ingress-traefik --create-namespace traefik traefik/traefik -f values.yml
         kubectl --namespace ingress-traefik rollout status daemonset traefik --timeout=90s

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 basegun.kubernetes.local" | sudo tee -a /etc/hosts

      - name: Checkout to code
        uses: actions/checkout@v2

      - name: Build and install basegun with helm and test it's running
        run: |
         BUILD_TARGET=test TAG=$(make get-current-tag) docker-compose -f docker-compose-dev.yml build backend
         BUILD_TARGET=test TAG=$(make get-current-tag) docker-compose -f docker-compose-dev.yml build frontend
         helm upgrade --install basegun ./infra/kube/basegun/  \
           --set="ingress.hosts[0].host=basegun.kubernetes.local" \
           --set="ingress.hosts[0].paths[0].path=/" \
           --set="ingress.hosts[0].paths[0].pathType=Prefix"  \
           --set="backend.secret.create=true" \
           --set="backend.image.repository=basegun-backend" \
           --set="backend.image.tag=$(make get-current-tag)-dev" \
           --set="frontend.image.repository=basegun-frontend" \
           --set="frontend.image.tag=$(make get-current-tag)-dev" \
           --set="backend.secret.values.X_OVH_TOKEN=test" \
           --set="backend.secret.values.API_OVH_TOKEN=test"
         for i in $(kubectl get deploy -o name); do kubectl rollout status $i -w --timeout=130s; done

      - name: Display pod logs on failure
        if: ${{ job.status != 'Success' }}
        run: |
          kubectl describe pods
          kubectl logs --all-containers=true --tail=100 

      - name: Test unitests on backend
        run : |
         kubectl exec deploy/basegun-backend -c basegun-backend -- python -m unittest discover -v
      
      - name: Test frontend
        run: |
         curl -o /dev/null basegun.kubernetes.local
