on:
  workflow_run:
    workflows: ["Test on kubernetes"]
    branches: [enh/kube]
    types: 
      - completed


name: Deploy on KUBE
jobs:
  deploy-kube:
    uses: ./.github/workflows/change-values.yml
    with:
      namespace: "basegun-preprod" # reuse environment github in namespace
      branch: ${{ github.ref_name }}
    secrets:
      # environment dependant
      KUBECONFIG: ${{ secrets.PREPROD_K8_CONFIG }}
      X_OVH_TOKEN: ${{ secrets.PREPROD_OVH_TOKEN }}

      # static variables
      OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
      OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
      OS_USERNAME: ${{ secrets.OS_USERNAME }}
      API_OVH_TOKEN: ${{ secrets.API_OVH_TOKEN }}
      JOB_GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN  }}