on:
  # only work when code is on main branch
  workflow_dispatch:
  push:
    branches:
      - 'enh/kube'
name: Deploy on KUBE
jobs:
  deploy-kube:
    uses: ./.github/workflows/change-values.yml
    with:
      namespace: "basegun-preprod" # reuse environment github in namespace
      branch: ${{ github.ref_name }}
    secrets:
      # environment dependant
      SA_SECRET: ${{ secrets.PREPROD_K8_TOKEN }}
      X_OVH_TOKEN: ${{ secrets.PREPROD_OVH_TOKEN }}

      # static variables
      CLUSTER_URL: ${{ secrets.CLUSTER_URL }}
      OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
      OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
      OS_USERNAME: ${{ secrets.OS_USERNAME }}
      API_OVH_TOKEN: ${{ secrets.API_OVH_TOKEN }}
      JOB_GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN  }}